---
#------------------------------------------------------------------
# My First GitHub Actions
#
# This is a basic workflow to help you get started with Actions
#------------------------------------------------------------------

name: CI/CD

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  setup:
    name: Setup A Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2
      
      - name: Install packages
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test
